version: '3.7'

services:
  postgres:
    container_name: postgres
    image: postgres:13.4-alpine
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    logging:
      driver: none

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.9.7-alpine
    environment:
      - RABBITMQ_DEFAULT_VHOST=vhost
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=pass
    logging:
      driver: none

  django:
    container_name: django
    build: ./
    volumes:
      - ./src:/src:rw
      - ./.env:/src/core/.env
    depends_on:
      - postgres
    ports:
      - 8000:8000
    environment:
      PROCESS: DEV_DJANGO

  celery:
    container_name: celery
    build: ./
    volumes:
      - ./src:/src:rw
      - ./.env:/src/core/.env
    depends_on:
      - postgres
      - rabbitmq
    environment:
      PROCESS: DEV_CELERY
